# Generated by Django 4.0.4 on 2022-05-29 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_image_location_delete_photo_image_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploader',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.category'),
        ),
    ]
