# Generated by Django 4.0.4 on 2022-05-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
