# Generated by Django 4.0.4 on 2022-05-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_image_location_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
